### ISSUE TITLE
HTTPS sites not supported

### ISSUE THREAD

**Issue by ghost** [brettalton/phpinfo-compare#2]
The curl_website function only works with http url, https urls are not accepted by the regex.

**Comment by brettalton** [comment]
It does work with HTTPS, just not if the SSL certificate is invalid. This thread has more info on the matter: [https://stackoverflow.com/questions/4372710/php-curl-https](https://stackoverflow.com/questions/4372710/php-curl-httpsm). You'll have to add,

`curl_setopt($ch,CURLOPT_SSL_VERIFYPEER, false)`

to curl_website to allow insecure connections. Cheers.

**Comment by ghost** [comment]
Look at line #265 of compare.php
`if (preg_match('/^http:\/\//i',$url))`

The function (curl_website) returns FALSE if a https url is passed.

**Comment by brettalton** [comment]
You're absolutely correct, thanks for spotting that! Fixed in referenced commit above (see: [https://github.com/brettalton/phpinfo-compare/commit/8104201ba5302cc48c38c1dbb6541b9fd69f8aef](https://github.com/brettalton/phpinfo-compare/commit/8104201ba5302cc48c38c1dbb6541b9fd69f8aef)
